In [1]:
import yfinance as yf

apple = yf.Ticker("aapl")

# show actions (dividends, splits)
apple.actions

# show dividends
apple.dividends

# show splits
apple.splits

Date
1987-06-16    2.0
2000-06-21    2.0
2005-02-28    2.0
2014-06-09    7.0
Name: Stock Splits, dtype: float64

In [2]:
import yfinance as yf

aapl = yf.Ticker("aapl")
aapl

yfinance.Ticker object <AAPL>

In [3]:
import yfinance as yf

aapl = yf.Ticker("aapl")

# get stock info
aapl_historical = aapl.history(start="2020-06-02", end="2020-06-07", interval="1m")
aapl_historical

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2020-06-02 09:30:00-04:00,320.74,321.68,320.62,321.22,952792,0,0
2020-06-02 09:31:00-04:00,321.23,321.31,320.78,321.03,90413,0,0
2020-06-02 09:32:00-04:00,321.02,321.93,321.02,321.67,192949,0,0
2020-06-02 09:33:00-04:00,321.71,321.74,321.28,321.44,113366,0,0
2020-06-02 09:34:00-04:00,321.43,321.94,321.43,321.55,101503,0,0
...,...,...,...,...,...,...,...
2020-06-05 15:55:00-04:00,330.62,330.88,330.47,330.76,187683,0,0
2020-06-05 15:56:00-04:00,330.75,330.81,330.35,330.50,153105,0,0
2020-06-05 15:57:00-04:00,330.50,330.80,330.40,330.45,144010,0,0
2020-06-05 15:58:00-04:00,330.45,330.99,330.35,330.93,253691,0,0
2020-06-05 15:59:00-04:00,330.92,331.63,330.91,331.63,473898,0,0

In [4]:
tickers = yf.Tickers('msft aapl goog')

In [5]:
tickers

yfinance.Tickers object <MSFT,AAPL,GOOG>

In [100]:
# TICKERS OBJECT IS BROKEN
tickers.msft.info

AttributeError: 'Tickers' object has no attribute 'msft'

In [8]:
data = yf.download("AMZN AAPL GOOG", start="2017-01-01", end="2017-04-30", group_by = 'column')
data

[*********************100%***********************]  3 of 3 completed

             Adj Close                               Close              \
                  AAPL        AMZN        GOOG        AAPL        AMZN
Date
2017-01-03  110.392334  753.669983  786.140015  116.150002  753.669983
2017-01-04  110.268791  757.179993  786.900024  116.019997  757.179993
2017-01-05  110.829552  780.450012  794.020020  116.610001  780.450012
2017-01-06  112.065109  795.989990  806.150024  117.910004  795.989990
2017-01-09  113.091560  796.919983  806.650024  118.989998  796.919983
...                ...         ...         ...         ...         ...
2017-04-24  137.111542  907.409973  862.760010  143.639999  907.409973
2017-04-25  137.961105  907.619995  872.299988  144.529999  907.619995
2017-04-26  137.149704  909.289978  871.729980  143.679993  909.289978
2017-04-27  137.254684  918.380005  874.250000  143.789993  918.380005
2017-04-28  137.121063  924.989990  905.960022  143.649994  924.989990

                              High                                 Low  \
                  GOOG        AAPL        AMZN        GOOG        AAPL
Date
2017-01-03  786.140015  116.330002  758.760010  789.630005  114.760002
2017-01-04  786.900024  116.510002  759.679993  791.340027  115.750000
2017-01-05  794.020020  116.860001  782.400024  794.479980  115.809998
2017-01-06  806.150024  118.160004  799.440002  807.900024  116.470001
2017-01-09  806.650024  119.430000  801.770020  809.966003  117.940002
...                ...         ...         ...         ...         ...
2017-04-24  862.760010  143.949997  909.989990  863.450012  143.179993
2017-04-25  872.299988  144.899994  909.479980  875.000000  143.869995
2017-04-26  871.729980  144.600006  915.750000  876.049988  143.380005
2017-04-27  874.250000  144.160004  921.859985  875.400024  143.309998
2017-04-28  905.960022  144.300003  949.590027  916.849976  143.270004

                                          Open                          \
                  AMZN        GOOG        AAPL        AMZN        GOOG
Date
2017-01-03  747.700012  775.799988  115.800003  757.919983  778.809998
2017-01-04  754.200012  783.159973  115.849998  758.390015  788.359985
2017-01-05  760.260010  785.020020  115.919998  761.549988  786.080017
2017-01-06  778.479980  792.203979  116.779999  782.359985  795.260010
2017-01-09  791.770020  802.830017  117.949997  798.000000  806.400024
...                ...         ...         ...         ...         ...
2017-04-24  903.820007  849.859985  143.500000  908.679993  851.200012
2017-04-25  903.000000  862.809998  143.910004  907.039978  865.000000
2017-04-26  907.559998  867.747986  144.470001  910.299988  874.229980
2017-04-27  912.109985  870.380005  143.919998  914.390015  873.599976
2017-04-28  924.330017  905.770020  144.089996  948.830017  910.659973

              Volume
                AAPL     AMZN     GOOG
Date
2017-01-03  28781900  3521100  1657300
2017-01-04  21118100  2510500  1073000
2017-01-05  22193600  5830100  1335200
2017-01-06  31751900  5986200  1640200
2017-01-09  33561900  3446100  1274600
...              ...      ...      ...
2017-04-24  17134300  3122900  1372500
2017-04-25  18871500  3380600  1672000
2017-04-26  20041200  2608900  1237200
2017-04-27  14246300  5305500  2026800
2017-04-28  20860400  7364700  3276300

[81 rows x 18 columns]

In [9]:
data = yf.download("AMZN AAPL GOOG", start="2017-01-01", end="2017-04-30", group_by='tickers')
data

[*********************100%***********************]  3 of 3 completed

                  GOOG                                                  \
                  Open        High         Low       Close   Adj Close
Date
2017-01-03  778.809998  789.630005  775.799988  786.140015  786.140015
2017-01-04  788.359985  791.340027  783.159973  786.900024  786.900024
2017-01-05  786.080017  794.479980  785.020020  794.020020  794.020020
2017-01-06  795.260010  807.900024  792.203979  806.150024  806.150024
2017-01-09  806.400024  809.966003  802.830017  806.650024  806.650024
...                ...         ...         ...         ...         ...
2017-04-24  851.200012  863.450012  849.859985  862.760010  862.760010
2017-04-25  865.000000  875.000000  862.809998  872.299988  872.299988
2017-04-26  874.229980  876.049988  867.747986  871.729980  871.729980
2017-04-27  873.599976  875.400024  870.380005  874.250000  874.250000
2017-04-28  910.659973  916.849976  905.770020  905.960022  905.960022

                           AMZN                                      \
             Volume        Open        High         Low       Close
Date
2017-01-03  1657300  757.919983  758.760010  747.700012  753.669983
2017-01-04  1073000  758.390015  759.679993  754.200012  757.179993
2017-01-05  1335200  761.549988  782.400024  760.260010  780.450012
2017-01-06  1640200  782.359985  799.440002  778.479980  795.989990
2017-01-09  1274600  798.000000  801.770020  791.770020  796.919983
...             ...         ...         ...         ...         ...
2017-04-24  1372500  908.679993  909.989990  903.820007  907.409973
2017-04-25  1672000  907.039978  909.479980  903.000000  907.619995
2017-04-26  1237200  910.299988  915.750000  907.559998  909.289978
2017-04-27  2026800  914.390015  921.859985  912.109985  918.380005
2017-04-28  3276300  948.830017  949.590027  924.330017  924.989990

                                       AAPL                          \
             Adj Close   Volume        Open        High         Low
Date
2017-01-03  753.669983  3521100  115.800003  116.330002  114.760002
2017-01-04  757.179993  2510500  115.849998  116.510002  115.750000
2017-01-05  780.450012  5830100  115.919998  116.860001  115.809998
2017-01-06  795.989990  5986200  116.779999  118.160004  116.470001
2017-01-09  796.919983  3446100  117.949997  119.430000  117.940002
...                ...      ...         ...         ...         ...
2017-04-24  907.409973  3122900  143.500000  143.949997  143.179993
2017-04-25  907.619995  3380600  143.910004  144.899994  143.869995
2017-04-26  909.289978  2608900  144.470001  144.600006  143.380005
2017-04-27  918.380005  5305500  143.919998  144.160004  143.309998
2017-04-28  924.989990  7364700  144.089996  144.300003  143.270004


                 Close   Adj Close    Volume
Date
2017-01-03  116.150002  110.392334  28781900
2017-01-04  116.019997  110.268791  21118100
2017-01-05  116.610001  110.829552  22193600
2017-01-06  117.910004  112.065109  31751900
2017-01-09  118.989998  113.091560  33561900
...                ...         ...       ...
2017-04-24  143.639999  137.111542  17134300
2017-04-25  144.529999  137.961105  18871500
2017-04-26  143.679993  137.149704  20041200
2017-04-27  143.789993  137.254684  14246300
2017-04-28  143.649994  137.121063  20860400

[81 rows x 18 columns]

In [69]:
aapl = yf.Ticker("aapl") 
aapl.info

{'zip': '95014',
 'sector': 'Technology',
 'fullTimeEmployees': 137000,
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. It also sells various related services. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, HomePod, iPod touch, and other Apple-branded and third-party accessories. It also provides digital content stores and streaming services; AppleCare support services; and iCloud, a cloud service, which stores music, photos, contacts, calendars, mail, documents, and others. In addition, the company offers various service, such as Apple Arcade, a game subscription service; Apple Card, a co-branded credit card; Apple News+, a subscription news and magazine service; and Apple Pay, a cashless payment service, as well as licenses its intellectual property, and provides other related services. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It sells and delivers third-party applications for its products through the App Store, Mac App Store, and Watch App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. has a collaboration with Google to develop COVID-19 tracking system for Android and iOS devices. Apple Inc. was founded in 1977 and is headquartered in Cupertino, California.',
 'city': 'Cupertino',
 'phone': '408-996-1010',
 'state': 'CA',
 'country': 'United States',
 'companyOfficers': [],
 'website': 'http://www.apple.com',
 'maxAge': 1,
 'address1': 'One Apple Park Way',
 'industry': 'Consumer Electronics',
 'previousClose': 342.99,
 'regularMarketOpen': 351.46,
 'twoHundredDayAverage': 293.4145,
 'trailingAnnualDividendYield': 0.008979853000000001,
 'payoutRatio': 0.24080000000000001,
 'volume24Hr': None,
 'regularMarketDayHigh': 353.0201,
 'navPrice': None,
 'averageDailyVolume10Day': 39594100,
 'totalAssets': None,
 'regularMarketPreviousClose': 342.99,
 'fiftyDayAverage': 314.71713,
 'trailingAnnualDividendRate': 3.08,
 'open': 351.46,
 'toCurrency': None,
 'averageVolume10days': 39594100,
 'expireDate': None,
 'yield': None,
 'algorithm': None,
 'dividendRate': 3.2800000000000002,
 'exDividendDate': 1588896000,
 'beta': 1.170435,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 349.07,
 'priceHint': 2,
 'currency': 'USD',
 'trailingPE': 27.65242,
 'regularMarketVolume': 8021292,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 1525510701056,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 42532806,
 'priceToSalesTrailing12Months': 5.692608,
 'dayLow': 349.07,
 'ask': 350.9,
 'ytdReturn': None,
 'askSize': 900,
 'volume': 8021292,
 'fiftyTwoWeekHigh': 354.77,
 'forwardPE': 23.68506,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': 1.58,
 'fiftyTwoWeekLow': 192.58,
 'bid': 350.58,
 'tradeable': False,
 'dividendYield': 0.009599999500000001,
 'bidSize': 800,
 'dayHigh': 353.0201,
 'exchange': 'NMS',
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-14400000',
 'quoteType': 'EQUITY',
 'symbol': 'AAPL',
 'messageBoardId': 'finmb_24937',
 'market': 'us_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': 5.572,
 'beta3Year': None,
 'profitMargins': 0.21350001000000002,
 'enterpriseToEbitda': 19.315,
 '52WeekChange': 0.7283447,
 'morningStarRiskRating': None,
 'forwardEps': 14.86,
 'revenueQuarterlyGrowth': None,
 'sharesOutstanding': 4334329856,
 'fundInceptionDate': None,
 'annualReportExpenseRatio': None,
 'bookValue': 18.137,
 'sharesShort': 34194077,
 'sharesPercentSharesOut': 0.007900001,
 'fundFamily': None,
 'lastFiscalYearEnd': 1569628800,
 'heldPercentInstitutions': 0.6211500000000001,
 'netIncomeToCommon': 57215000576,
 'trailingEps': 12.728,
 'lastDividendValue': None,
 'SandP52WeekChange': 0.05101192,
 'priceToBook': 19.405636,
 'heldPercentInsiders': 0.0006600000000000001,
 'nextFiscalYearEnd': 1632787200,
 'mostRecentQuarter': 1585353600,
 'shortRatio': 0.96,
 'sharesShortPreviousMonthDate': 1588204800,
 'floatShares': 4329870635,
 'enterpriseValue': 1493182709760,
 'threeYearAverageReturn': None,
 'lastSplitDate': 1402272000,
 'lastSplitFactor': '7:1',
 'legalType': None,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': -0.027,
 'dateShortInterest': 1590710400,
 'pegRatio': 2.42,
 'lastCapGain': None,
 'shortPercentOfFloat': 0.007900001,
 'sharesShortPriorMonth': 30124922,
 'category': None,
 'fiveYearAverageReturn': None,
 'regularMarketPrice': 351.46,
 'logo_url': 'https://logo.clearbit.com/apple.com'}

In [11]:
aapl = yf.Ticker("aapl")
aapl.info['forwardPE']

23.081427

In [12]:
aapl.info['dividendRate']

3.2800000000000002

In [13]:
aapl.dividends

Date
1987-05-11    0.00214
1987-08-10    0.00214
1987-11-17    0.00286
1988-02-12    0.00286
1988-05-16    0.00286
               ...
2019-05-10    0.77000
2019-08-09    0.77000
2019-11-07    0.77000
2020-02-07    0.77000
2020-05-08    0.82000
Name: Dividends, Length: 67, dtype: float64

In [14]:
import pandas as pd

tickers_list = ["aapl", "goog", "amzn", "BAC", "BA"] # example list
tickers_data = {} # empty dictionary

In [31]:
for ticker in tickers_list:
    ticker_object = yf.Ticker(ticker)

    #convert info() output from dictionary to dataframe
    temp = pd.DataFrame.from_dict(ticker_object.info, orient="index")
    temp.reset_index(inplace=True)
    temp.columns = ["Attribute", "Recent"]
    
    # add (ticker, dataframe) to main dictionary
    tickers_data[ticker] = temp

tickers_data

{'aapl':                  Attribute                                             Recent
 0                      zip                                              95014
 1                   sector                                         Technology
 2        fullTimeEmployees                                             137000
 3      longBusinessSummary  Apple Inc. designs, manufactures, and markets ...
 4                     city                                          Cupertino
 ..                     ...                                                ...
 116  sharesShortPriorMonth                                           30124922
 117               category                                               None
 118  fiveYearAverageReturn                                               None
 119     regularMarketPrice                                             344.72
 120               logo_url                https://logo.clearbit.com/apple.com

 [121 rows x 2 columns],
 'goog':                  Attribute                                             Recent
 0                      zip                                              94043
 1                   sector                             Communication Services
 2        fullTimeEmployees                                             123048
 3      longBusinessSummary  Alphabet Inc. provides online advertising serv...
 4                     city                                      Mountain View
 ..                     ...                                                ...
 116  sharesShortPriorMonth                                            3496044
 117               category                                               None
 118  fiveYearAverageReturn                                               None
 119     regularMarketPrice                                             1390.8
 120               logo_url                  https://logo.clearbit.com/abc.xyz

 [121 rows x 2 columns],
 'amzn':                  Attribute                                             Recent
 0                      zip                                         98109-5210
 1                   sector                                  Consumer Cyclical
 2        fullTimeEmployees                                             840400
 3      longBusinessSummary  Amazon.com, Inc. engages in the retail sale of...
 4                     city                                            Seattle
 ..                     ...                                                ...
 116  sharesShortPriorMonth                                            3505745
 117               category                                               None
 118  fiveYearAverageReturn                                               None
 119     regularMarketPrice                                             2526.6
 120               logo_url               https://logo.clearbit.com/amazon.com

 [121 rows x 2 columns],
 'BAC':                  Attribute                                             Recent
 0                      zip                                              28255
 1                   sector                                 Financial Services
 2        fullTimeEmployees                                             209000
 3      longBusinessSummary  Bank of America Corporation, through its subsi...
 4                     city                                          Charlotte
 ..                     ...                                                ...
 117  sharesShortPriorMonth                                          111069451
 118               category                                               None
 119  fiveYearAverageReturn                                               None
 120     regularMarketPrice                                              23.76
 121               logo_url        https://logo.clearbit.com/bankofamerica.com

 [122 rows x 2 columns],
 'BA':                  Attribute                                             Recent
 0                      zip                                         60606-1596
 1                   sector                                        Industrials
 2        fullTimeEmployees                                             161100
 3      longBusinessSummary  The Boeing Company, together with its subsidia...
 4                     city                                            Chicago
 ..                     ...                                                ...
 115  sharesShortPriorMonth                                           17995687
 116               category                                               None
 117  fiveYearAverageReturn                                               None
 118     regularMarketPrice                                             177.18
 119               logo_url               https://logo.clearbit.com/boeing.com

 [120 rows x 2 columns]}

In [32]:
# combine all the info dataframes for each ticker into a single data frame
combined_data = pd.concat(tickers_data)
combined_data = combined_data.reset_index()
combined_data

,level_0,level_1,Attribute,Recent
0,aapl,0,zip,95014
1,aapl,1,sector,Technology
2,aapl,2,fullTimeEmployees,137000
3,aapl,3,longBusinessSummary,"Apple Inc. designs, manufactures, and markets ..."
4,aapl,4,city,Cupertino
...,...,...,...,...
600,BA,115,sharesShortPriorMonth,17995687
601,BA,116,category,None
602,BA,117,fiveYearAverageReturn,None
603,BA,118,regularMarketPrice,177.18
604,BA,119,logo_url,https://logo.clearbit.com/boeing.com

In [34]:
del combined_data["level_1"] # clean up unnecessary column
combined_data.columns = ["Ticker", "Attribute", "Recent"] # update column names

combined_data

,Ticker,Attribute,Recent
0,aapl,zip,95014
1,aapl,sector,Technology
2,aapl,fullTimeEmployees,137000
3,aapl,longBusinessSummary,"Apple Inc. designs, manufactures, and markets ..."
4,aapl,city,Cupertino
...,...,...,...
600,BA,sharesShortPriorMonth,17995687
601,BA,category,None
602,BA,fiveYearAverageReturn,None
603,BA,regularMarketPrice,177.18
604,BA,logo_url,https://logo.clearbit.com/boeing.com

In [44]:
employees = combined_data[combined_data["Attribute"]=="fullTimeEmployees"].reset_index()
del employees["index"] # clean up unnecessary column

employees

  Ticker          Attribute  Recent
0   aapl  fullTimeEmployees  137000
1   goog  fullTimeEmployees  123048
2   amzn  fullTimeEmployees  840400
3    BAC  fullTimeEmployees  209000
4     BA  fullTimeEmployees  161100

In [45]:
employees_sorted = employees.sort_values('Recent',ascending=False)
employees_sorted

  Ticker          Attribute  Recent
2   amzn  fullTimeEmployees  840400
3    BAC  fullTimeEmployees  209000
4     BA  fullTimeEmployees  161100
0   aapl  fullTimeEmployees  137000
1   goog  fullTimeEmployees  123048

In [70]:
aapl.info["marketCap"]

1525510701056

In [71]:
aapl.info["volume"]

8021292

In [74]:
aapl.info["averageVolume"]

42532806

In [75]:
aapl.info["averageVolume10days"]

39594100

In [78]:
aapl_historical = aapl.history(period="max", interval="1wk")
aapl_historical

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1980-12-08,0.41,0.41,0.41,0.41,117258400.0,0.0,0.0
1980-12-15,0.39,0.40,0.36,0.40,122533600.0,0.0,0.0
1980-12-22,0.42,0.50,0.42,0.50,46972800.0,0.0,0.0
1980-12-29,0.51,0.51,0.48,0.49,54863200.0,0.0,0.0
1981-01-05,0.48,0.48,0.43,0.45,49476000.0,0.0,0.0
...,...,...,...,...,...,...,...
2020-05-25,323.50,324.24,313.09,317.94,131406500.0,0.0,0.0
2020-06-01,317.75,331.75,317.21,331.50,124434000.0,0.0,0.0
2020-06-08,330.25,354.77,327.32,338.80,202921700.0,0.0,0.0
2020-06-15,333.25,345.68,332.58,342.99,34642900.0,0.0,0.0
2020-06-16,333.25,353.02,349.07,351.53,10708995.0,0.0,0.0

In [79]:
aapl.info["fiftyTwoWeekHigh"]

354.77

In [81]:
aapl.options

('2020-06-19',
 '2020-06-26',
 '2020-07-02',
 '2020-07-10',
 '2020-07-17',
 '2020-07-24',
 '2020-07-31',
 '2020-08-21',
 '2020-09-18',
 '2020-10-16',
 '2020-11-20',
 '2020-12-18',
 '2021-01-15',
 '2021-06-18',
 '2021-09-17',
 '2022-01-21',
 '2022-06-17',
 '2022-09-16')

In [95]:
# get option chain calls data for specific expiration date
opt = aapl.option_chain(date='2020-07-24')
opt.calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL200724C00170000,2020-06-12 13:38:07,170.0,175.11,178.50,181.85,0.000000,0.000000,1.0,0.0,1.240971,True,REGULAR,USD
1,AAPL200724C00230000,2020-06-09 19:19:41,230.0,115.11,118.35,121.55,0.000000,0.000000,NaN,1.0,0.749514,True,REGULAR,USD
2,AAPL200724C00250000,2020-06-15 15:35:19,250.0,88.60,99.40,102.15,0.000000,0.000000,1.0,3.0,0.692874,True,REGULAR,USD
3,AAPL200724C00255000,2020-06-12 13:50:07,255.0,92.60,93.60,96.90,0.000000,0.000000,1.0,0.0,0.617680,True,REGULAR,USD
4,AAPL200724C00260000,2020-06-16 13:46:57,260.0,93.00,88.80,92.00,4.160004,4.682580,1.0,5.0,0.598271,True,REGULAR,USD
5,AAPL200724C00265000,2020-06-16 14:49:37,265.0,85.98,83.20,86.70,8.750000,11.329794,2.0,54.0,0.530034,True,REGULAR,USD
6,AAPL200724C00270000,2020-06-10 14:26:57,270.0,80.50,79.70,82.85,0.000000,0.000000,NaN,11.0,0.593144,True,REGULAR,USD
7,AAPL200724C00275000,2020-06-12 14:44:44,275.0,67.92,74.30,77.30,0.000000,0.000000,2.0,6.0,0.531499,True,REGULAR,USD
8,AAPL200724C00280000,2020-06-12 17:59:03,280.0,59.02,69.60,72.30,0.000000,0.000000,2.0,18.0,0.508794,True,REGULAR,USD
9,AAPL200724C00285000,2020-06-10 18:32:31,285.0,70.35,64.60,67.35,0.000000,0.000000,1.0,10.0,0.547856,True,REGULAR,USD
10,AAPL200724C00290000,2020-06-15 16:22:57,290.0,52.80,59.85,63.00,0.000000,0.000000,2.0,113.0,0.541264,True,REGULAR,USD
11,AAPL200724C00295000,2020-06-10 19:12:42,295.0,59.85,55.30,57.90,0.000000,0.000000,28.0,35.0,0.501836,True,REGULAR,USD
12,AAPL200724C00300000,2020-06-12 17:46:57,300.0,41.50,51.25,52.80,0.000000,0.000000,8.0,117.0,0.462896,True,REGULAR,USD
13,AAPL200724C00302500,2020-06-11 15:14:49,302.5,48.30,49.10,50.80,0.000000,0.000000,NaN,5.0,0.464117,True,REGULAR,USD
14,AAPL200724C00305000,2020-06-16 13:56:31,305.0,49.10,46.75,48.55,9.570000,24.209461,2.0,23.0,0.455145,True,REGULAR,USD
15,AAPL200724C00307500,2020-06-15 13:54:30,307.5,34.47,45.60,46.90,0.000000,0.000000,1.0,31.0,0.465765,True,REGULAR,USD
16,AAPL200724C00310000,2020-06-16 14:51:57,310.0,42.50,42.40,44.05,5.049999,13.484644,1.0,40.0,0.435553,True,REGULAR,USD
17,AAPL200724C00312500,2020-06-15 16:24:56,312.5,33.75,40.10,42.70,0.000000,0.000000,2.0,7.0,0.453069,True,REGULAR,USD
18,AAPL200724C00315000,2020-06-15 14:30:16,315.0,29.05,37.20,40.05,0.000000,0.000000,3.0,8.0,0.429205,True,REGULAR,USD
19,AAPL200724C00317500,2020-06-10 19:56:01,317.5,39.27,36.00,38.15,0.000000,0.000000,6.0,28.0,0.427313,True,REGULAR,USD
20,AAPL200724C00320000,2020-06-16 14:13:55,320.0,36.42,33.95,36.00,5.349998,17.219180,5.0,146.0,0.417303,True,REGULAR,USD
21,AAPL200724C00322500,2020-06-16 13:35:26,322.5,33.15,32.20,33.60,7.040001,26.962854,1.0,33.0,0.399847,True,REGULAR,USD
22,AAPL200724C00325000,2020-06-15 18:48:28,325.0,27.38,30.25,31.50,0.000000,0.000000,15.0,96.0,0.390051,True,REGULAR,USD
23,AAPL200724C00327500,2020-06-16 14:44:27,327.5,29.40,28.35,29.25,8.600000,41.346157,2.0,83.0,0.375617,True,REGULAR,USD
24,AAPL200724C00330000,2020-06-16 14:44:27,330.0,27.44,25.70,26.60,4.840000,21.415930,18.0,236.0,0.350531,True,REGULAR,USD
25,AAPL200724C00332500,2020-06-16 14:44:27,332.5,25.25,24.25,24.60,5.250000,26.250000,6.0,60.0,0.341437,True,REGULAR,USD
26,AAPL200724C00335000,2020-06-16 14:53:06,335.0,22.48,22.65,23.00,3.359999,17.573214,15.0,447.0,0.340918,True,REGULAR,USD
27,AAPL200724C00337500,2020-06-16 14:43:40,337.5,22.05,21.80,22.10,4.400000,24.929176,25.0,175.0,0.355292,True,REGULAR,USD
28,AAPL200724C00340000,2020-06-16 14:55:08,340.0,19.00,19.55,19.80,2.700001,16.564423,72.0,530.0,0.335608,True,REGULAR,USD
29,AAPL200724C00342500,2020-06-16 14:21:25,342.5,19.30,18.50,18.75,4.449999,29.966320,27.0,115.0,0.343268,True,REGULAR,USD
30,AAPL200724C00345000,2020-06-16 14:54:50,345.0,15.90,17.10,17.35,2.349999,17.343168,64.0,390.0,0.341498,True,REGULAR,USD
31,AAPL200724C00347500,2020-06-16 14:40:46,347.5,16.15,15.55,15.75,4.000000,32.921810,39.0,161.0,0.333930,True,REGULAR,USD
32,AAPL200724C00350000,2020-06-16 14:52:50,350.0,13.50,14.30,14.50,2.450000,22.171944,344.0,1053.0,0.332709,False,REGULAR,USD
33,AAPL200724C00352500,2020-06-16 14:52:37,352.5,12.40,13.00,13.25,3.900000,45.882347,113.0,21.0,0.330024,False,REGULAR,USD
34,AAPL200724C00355000,2020-06-16 14:46:06,355.0,11.35,11.55,11.75,2.350000,26.111115,83.0,514.0,0.320380,False,REGULAR,USD
35,AAPL200724C00357500,2020-06-16 14:52:57,357.5,9.75,10.60,10.90,1.000000,11.428572,12.0,33.0,0.323646,False,REGULAR,USD
36,AAPL200724C00360000,2020-06-16 14:53:24,360.0,8.85,9.35,9.50,1.560000,21.399183,131.0,579.0,0.313056,False,REGULAR,USD
37,AAPL200724C00362500,2020-06-16 14:53:13,362.5,8.05,8.50,8.70,2.100000,35.294125,15.0,12.0,0.314582,False,REGULAR,USD
38,AAPL200724C00365000,2020-06-16 14:52:06,365.0,7.40,7.55,7.80,1.350000,22.314047,32.0,172.0,0.312293,False,REGULAR,USD
39,AAPL200724C00367500,2020-06-16 14:45:06,367.5,6.69,6.75,6.95,1.290000,23.888890,6.0,11.0,0.309669,False,REGULAR,USD
40,AAPL200724C00370000,2020-06-16 14:39:05,370.0,6.47,5.95,6.15,2.120000,48.735630,54.0,594.0,0.306709,False,REGULAR,USD
41,AAPL200724C00372500,2020-06-16 13:57:32,372.5,6.00,5.15,5.30,2.090000,53.452680,3.0,17.0,0.300666,False,REGULAR,USD
42,AAPL200724C00375000,2020-06-16 14:45:48,375.0,4.45,4.60,4.80,0.650000,17.105259,46.0,248.0,0.302436,False,REGULAR,USD
43,AAPL200724C00380000,2020-06-16 14:41:32,380.0,3.75,3.45,3.65,1.190000,46.484380,19.0,257.0,0.297370,False,REGULAR,USD
44,AAPL200724C00385000,2020-06-16 14:51:10,385.0,2.69,2.71,2.82,0.630000,30.582531,11.0,263.0,0.296028,False,REGULAR,USD
45,AAPL200724C00390000,2020-06-16 14:39:43,390.0,2.38,1.96,2.25,0.760000,46.913586,18.0,191.0,0.298774,False,REGULAR,USD
46,AAPL200724C00395000,2020-06-16 14:54:59,395.0,1.53,1.54,1.78,0.310000,25.409830,146.0,658.0,0.301032,False,REGULAR,USD
47,AAPL200724C00400000,2020-06-16 14:49:52,400.0,1.34,1.22,1.30,0.290000,27.619057,267.0,921.0,0.297737,False,REGULAR,USD
48,AAPL200724C00405000,2020-06-16 14:21:16,405.0,1.21,1.02,1.13,0.390000,47.560980,19.0,124.0,0.307380,False,REGULAR,USD
49,AAPL200724C00410000,2020-06-16 14:54:00,410.0,0.82,0.83,0.93,0.070000,9.333332,20.0,112.0,0.312751,False,REGULAR,USD
50,AAPL200724C00415000,2020-06-16 14:39:07,415.0,0.80,0.71,0.80,0.300000,60.000004,6.0,17.0,0.320563,False,REGULAR,USD
51,AAPL200724C00420000,2020-06-16 14:18:26,420.0,0.71,0.56,0.75,0.170000,31.481474,5.0,105.0,0.333503,False,REGULAR,USD
52,AAPL200724C00425000,2020-06-16 14:19:08,425.0,0.62,0.54,0.63,0.140000,29.166672,1.0,36.0,0.338996,False,REGULAR,USD
53,AAPL200724C00435000,2020-06-15 16:28:26,435.0,0.37,NaN,NaN,0.000000,0.000000,NaN,NaN,0.000000,False,REGULAR,USD

In [96]:
opt.puts

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL200724P00180000,2020-06-15 14:17:59,180.0,0.20,0.00,0.18,0.000000,0.000000,42.0,22,0.775393,False,REGULAR,USD
1,AAPL200724P00190000,2020-06-15 16:28:26,190.0,0.18,0.00,0.22,0.000000,0.000000,10.0,20,0.732425,False,REGULAR,USD
2,AAPL200724P00195000,2020-06-15 04:13:08,195.0,0.39,0.00,0.24,0.000000,0.000000,NaN,1,0.710940,False,REGULAR,USD
3,AAPL200724P00200000,2020-06-15 14:51:12,200.0,0.40,0.03,0.27,0.000000,0.000000,13.0,14,0.700198,False,REGULAR,USD
4,AAPL200724P00205000,2020-06-12 17:35:31,205.0,0.55,0.06,0.31,0.000000,0.000000,NaN,1,0.689456,False,REGULAR,USD
5,AAPL200724P00210000,2020-06-15 18:07:35,210.0,0.33,0.09,0.34,0.000000,0.000000,1.0,3,0.673831,False,REGULAR,USD
6,AAPL200724P00215000,2020-06-12 14:35:13,215.0,0.32,0.13,0.36,0.000000,0.000000,9.0,10,0.656253,False,REGULAR,USD
7,AAPL200724P00220000,2020-06-16 14:19:25,220.0,0.28,0.15,0.43,-0.070000,-19.999998,105.0,8,0.642582,False,REGULAR,USD
8,AAPL200724P00225000,2020-06-15 17:48:53,225.0,0.50,0.29,0.42,0.000000,0.000000,4.0,14,0.632816,False,REGULAR,USD
9,AAPL200724P00230000,2020-06-16 13:41:27,230.0,0.31,0.27,0.48,-0.140000,-31.111107,1.0,7,0.609379,False,REGULAR,USD
10,AAPL200724P00235000,2020-06-15 19:02:49,235.0,0.55,0.33,0.54,0.000000,0.000000,10.0,14,0.594731,False,REGULAR,USD
11,AAPL200724P00240000,2020-06-16 14:45:43,240.0,0.50,0.39,0.66,-0.440000,-46.808510,2.0,17,0.583989,False,REGULAR,USD
12,AAPL200724P00245000,2020-06-15 16:19:52,245.0,0.95,0.51,0.60,0.000000,0.000000,192.0,192,0.561040,False,REGULAR,USD
13,AAPL200724P00250000,2020-06-16 14:21:24,250.0,0.60,0.62,0.71,-0.260000,-30.232557,12.0,217,0.550053,False,REGULAR,USD
14,AAPL200724P00255000,2020-06-16 13:34:33,255.0,0.75,0.68,0.77,-0.430000,-36.440678,5.0,40,0.530034,False,REGULAR,USD
15,AAPL200724P00260000,2020-06-15 18:50:59,260.0,1.02,0.80,0.87,0.000000,0.000000,44.0,198,0.515386,False,REGULAR,USD
16,AAPL200724P00265000,2020-06-15 16:46:00,265.0,1.56,0.94,1.04,0.000000,0.000000,103.0,163,0.503667,False,REGULAR,USD
17,AAPL200724P00270000,2020-06-16 13:54:33,270.0,1.03,1.07,1.16,-1.020000,-49.756100,5.0,198,0.490972,False,REGULAR,USD
18,AAPL200724P00275000,2020-06-16 14:28:54,275.0,1.16,1.20,1.26,-1.360000,-53.968254,8.0,217,0.470464,False,REGULAR,USD
19,AAPL200724P00280000,2020-06-16 14:24:07,280.0,1.30,1.36,1.45,-0.560000,-30.107530,5.0,512,0.455816,False,REGULAR,USD
20,AAPL200724P00285000,2020-06-16 14:40:41,285.0,1.54,1.63,1.71,-0.580000,-27.358488,2.0,249,0.443853,False,REGULAR,USD
21,AAPL200724P00290000,2020-06-16 14:53:03,290.0,1.97,1.75,2.19,-0.430000,-17.916668,1.0,151,0.441534,False,REGULAR,USD
22,AAPL200724P00295000,2020-06-16 14:38:46,295.0,2.11,2.14,2.24,-0.890000,-29.666670,3.0,88,0.412970,False,REGULAR,USD
23,AAPL200724P00300000,2020-06-16 14:42:06,300.0,2.51,2.44,2.55,-0.840000,-25.074625,19.0,384,0.396674,False,REGULAR,USD
24,AAPL200724P00302500,2020-06-15 18:08:06,302.5,3.75,2.84,2.95,0.000000,0.000000,1.0,29,0.398444,False,REGULAR,USD
25,AAPL200724P00305000,2020-06-16 14:18:05,305.0,2.70,2.91,3.05,-2.900000,-51.785717,27.0,104,0.386237,False,REGULAR,USD
26,AAPL200724P00307500,2020-06-16 14:47:04,307.5,3.30,3.15,3.30,-3.000000,-47.619053,6.0,20,0.379645,False,REGULAR,USD
27,AAPL200724P00310000,2020-06-16 14:53:22,310.0,3.80,3.60,3.75,-1.200000,-24.000000,27.0,311,0.379706,False,REGULAR,USD
28,AAPL200724P00312500,2020-06-16 14:23:20,312.5,3.55,3.75,3.90,-1.960000,-35.571693,4.0,73,0.367804,False,REGULAR,USD
29,AAPL200724P00315000,2020-06-16 14:37:47,315.0,3.75,4.20,4.35,-2.230000,-37.290970,31.0,225,0.365607,False,REGULAR,USD
30,AAPL200724P00317500,2020-06-16 14:02:47,317.5,4.30,4.60,4.75,-4.729999,-52.380947,6.0,71,0.360541,False,REGULAR,USD
31,AAPL200724P00320000,2020-06-16 14:41:41,320.0,4.90,4.90,5.10,-2.050000,-29.496399,15.0,230,0.352912,False,REGULAR,USD
32,AAPL200724P00322500,2020-06-16 14:44:40,322.5,5.50,5.70,5.90,-1.900000,-25.675678,1.0,24,0.357428,False,REGULAR,USD
33,AAPL200724P00325000,2020-06-16 14:25:42,325.0,5.50,6.15,6.35,-2.650000,-32.515335,18.0,170,0.350409,False,REGULAR,USD
34,AAPL200724P00327500,2020-06-16 13:52:39,327.5,6.30,6.45,6.65,-5.349999,-45.922745,13.0,134,0.338447,False,REGULAR,USD
35,AAPL200724P00330000,2020-06-16 14:53:49,330.0,7.85,7.05,7.25,-2.300000,-22.660097,59.0,221,0.333503,False,REGULAR,USD
36,AAPL200724P00332500,2020-06-15 18:40:54,332.5,10.01,7.70,7.90,0.000000,0.000000,12.0,42,0.328620,False,REGULAR,USD
37,AAPL200724P00335000,2020-06-16 14:42:10,335.0,8.50,8.40,8.60,-2.700000,-24.107141,11.0,130,0.323676,False,REGULAR,USD
38,AAPL200724P00337500,2020-06-16 14:38:16,337.5,9.25,9.20,9.45,-3.300000,-26.294823,6.0,52,0.320991,False,REGULAR,USD
39,AAPL200724P00340000,2020-06-16 14:47:25,340.0,10.25,10.10,10.30,-3.270001,-24.186394,18.0,242,0.316901,False,REGULAR,USD
40,AAPL200724P00342500,2020-06-16 14:55:09,342.5,12.00,10.95,11.15,-2.750000,-18.644068,3.0,135,0.311347,False,REGULAR,USD
41,AAPL200724P00345000,2020-06-16 14:38:05,345.0,11.70,11.95,12.15,-4.120000,-26.042984,9.0,103,0.307777,False,REGULAR,USD
42,AAPL200724P00347500,2020-06-16 14:34:02,347.5,12.20,12.90,13.15,-4.200000,-25.609755,2.0,54,0.302680,False,REGULAR,USD
43,AAPL200724P00350000,2020-06-16 14:52:08,350.0,14.95,14.05,14.25,-3.070001,-17.036629,32.0,210,0.298255,True,REGULAR,USD
44,AAPL200724P00352500,2020-06-16 14:48:20,352.5,15.50,15.20,15.45,0.550000,3.678931,7.0,1,0.294441,True,REGULAR,USD
45,AAPL200724P00355000,2020-06-16 14:37:49,355.0,15.50,15.45,15.60,-5.420000,-25.908222,11.0,59,0.265602,True,REGULAR,USD
46,AAPL200724P00357500,2020-06-16 14:34:02,357.5,16.90,17.95,18.20,-5.770001,-25.452143,9.0,1,0.289619,True,REGULAR,USD
47,AAPL200724P00360000,2020-06-12 15:22:06,360.0,28.90,20.15,20.35,0.000000,0.000000,18.0,55,0.302436,True,REGULAR,USD
48,AAPL200724P00365000,2020-06-10 17:44:00,365.0,21.07,22.15,22.75,0.000000,0.000000,NaN,1,0.279426,True,REGULAR,USD
49,AAPL200724P00370000,2020-06-11 19:36:28,370.0,36.90,25.55,26.00,0.000000,0.000000,NaN,3,0.268440,True,REGULAR,USD
50,AAPL200724P00385000,2020-06-10 19:09:30,385.0,35.00,36.15,38.75,0.000000,0.000000,NaN,2,0.281990,True,REGULAR,USD
51,AAPL200724P00390000,2020-06-15 15:23:22,390.0,54.20,40.15,42.90,0.000000,0.000000,2.0,2,0.270149,True,REGULAR,USD
52,AAPL200724P00395000,2020-06-10 15:30:40,395.0,44.82,45.90,47.75,0.000000,0.000000,NaN,2,0.284309,True,REGULAR,USD
53,AAPL200724P00400000,2020-06-15 14:23:33,400.0,64.70,50.50,53.95,0.000000,0.000000,1.0,1,0.359992,True,REGULAR,USD
54,AAPL200724P00405000,2020-06-12 16:34:25,405.0,66.19,55.30,58.65,0.000000,0.000000,1.0,1,0.369086,True,REGULAR,USD

In [99]:
opt

Options(calls=         contractSymbol       lastTradeDate  strike  lastPrice     bid  \
0   AAPL200724C00170000 2020-06-12 13:38:07   170.0     175.11  178.50
1   AAPL200724C00230000 2020-06-09 19:19:41   230.0     115.11  118.35
2   AAPL200724C00250000 2020-06-15 15:35:19   250.0      88.60   99.40
3   AAPL200724C00255000 2020-06-12 13:50:07   255.0      92.60   93.60
4   AAPL200724C00260000 2020-06-16 13:46:57   260.0      93.00   88.80
5   AAPL200724C00265000 2020-06-16 14:49:37   265.0      85.98   83.20
6   AAPL200724C00270000 2020-06-10 14:26:57   270.0      80.50   79.70
7   AAPL200724C00275000 2020-06-12 14:44:44   275.0      67.92   74.30
8   AAPL200724C00280000 2020-06-12 17:59:03   280.0      59.02   69.60
9   AAPL200724C00285000 2020-06-10 18:32:31   285.0      70.35   64.60
10  AAPL200724C00290000 2020-06-15 16:22:57   290.0      52.80   59.85
11  AAPL200724C00295000 2020-06-10 19:12:42   295.0      59.85   55.30
12  AAPL200724C00300000 2020-06-12 17:46:57   300.0      41.50   51.25
13  AAPL200724C00302500 2020-06-11 15:14:49   302.5      48.30   49.10
14  AAPL200724C00305000 2020-06-16 13:56:31   305.0      49.10   46.75
15  AAPL200724C00307500 2020-06-15 13:54:30   307.5      34.47   45.60
16  AAPL200724C00310000 2020-06-16 14:51:57   310.0      42.50   42.40
17  AAPL200724C00312500 2020-06-15 16:24:56   312.5      33.75   40.10
18  AAPL200724C00315000 2020-06-15 14:30:16   315.0      29.05   37.20
19  AAPL200724C00317500 2020-06-10 19:56:01   317.5      39.27   36.00
20  AAPL200724C00320000 2020-06-16 14:13:55   320.0      36.42   33.95
21  AAPL200724C00322500 2020-06-16 13:35:26   322.5      33.15   32.20
22  AAPL200724C00325000 2020-06-15 18:48:28   325.0      27.38   30.25
23  AAPL200724C00327500 2020-06-16 14:44:27   327.5      29.40   28.35
24  AAPL200724C00330000 2020-06-16 14:44:27   330.0      27.44   25.70
25  AAPL200724C00332500 2020-06-16 14:44:27   332.5      25.25   24.25
26  AAPL200724C00335000 2020-06-16 14:53:06   335.0      22.48   22.65
27  AAPL200724C00337500 2020-06-16 14:43:40   337.5      22.05   21.80
28  AAPL200724C00340000 2020-06-16 14:55:08   340.0      19.00   19.55
29  AAPL200724C00342500 2020-06-16 14:21:25   342.5      19.30   18.50
30  AAPL200724C00345000 2020-06-16 14:54:50   345.0      15.90   17.10
31  AAPL200724C00347500 2020-06-16 14:40:46   347.5      16.15   15.55
32  AAPL200724C00350000 2020-06-16 14:52:50   350.0      13.50   14.30
33  AAPL200724C00352500 2020-06-16 14:52:37   352.5      12.40   13.00
34  AAPL200724C00355000 2020-06-16 14:46:06   355.0      11.35   11.55
35  AAPL200724C00357500 2020-06-16 14:52:57   357.5       9.75   10.60
36  AAPL200724C00360000 2020-06-16 14:53:24   360.0       8.85    9.35
37  AAPL200724C00362500 2020-06-16 14:53:13   362.5       8.05    8.50
38  AAPL200724C00365000 2020-06-16 14:52:06   365.0       7.40    7.55
39  AAPL200724C00367500 2020-06-16 14:45:06   367.5       6.69    6.75
40  AAPL200724C00370000 2020-06-16 14:39:05   370.0       6.47    5.95
41  AAPL200724C00372500 2020-06-16 13:57:32   372.5       6.00    5.15
42  AAPL200724C00375000 2020-06-16 14:45:48   375.0       4.45    4.60
43  AAPL200724C00380000 2020-06-16 14:41:32   380.0       3.75    3.45
44  AAPL200724C00385000 2020-06-16 14:51:10   385.0       2.69    2.71
45  AAPL200724C00390000 2020-06-16 14:39:43   390.0       2.38    1.96
46  AAPL200724C00395000 2020-06-16 14:54:59   395.0       1.53    1.54
47  AAPL200724C00400000 2020-06-16 14:49:52   400.0       1.34    1.22
48  AAPL200724C00405000 2020-06-16 14:21:16   405.0       1.21    1.02
49  AAPL200724C00410000 2020-06-16 14:54:00   410.0       0.82    0.83
50  AAPL200724C00415000 2020-06-16 14:39:07   415.0       0.80    0.71
51  AAPL200724C00420000 2020-06-16 14:18:26   420.0       0.71    0.56
52  AAPL200724C00425000 2020-06-16 14:19:08   425.0       0.62    0.54
53  AAPL200724C00435000 2020-06-15 16:28:26   435.0       0.37     NaN

       ask    change  percentChange  volume  openInterest  impliedVolatility  \
0   181.85  0.000000       0.000000     1.0           0.0           1.240971
1   121.55  0.000000       0.000000     NaN           1.0           0.749514
2   102.15  0.000000       0.000000     1.0           3.0           0.692874
3    96.90  0.000000       0.000000     1.0           0.0           0.617680
4    92.00  4.160004       4.682580     1.0           5.0           0.598271
5    86.70  8.750000      11.329794     2.0          54.0           0.530034
6    82.85  0.000000       0.000000     NaN          11.0           0.593144
7    77.30  0.000000       0.000000     2.0           6.0           0.531499
8    72.30  0.000000       0.000000     2.0          18.0           0.508794
9    67.35  0.000000       0.000000     1.0          10.0           0.547856
10   63.00  0.000000       0.000000     2.0         113.0           0.541264
11   57.90  0.000000       0.000000    28.0          35.0           0.501836
12   52.80  0.000000       0.000000     8.0         117.0           0.462896
13   50.80  0.000000       0.000000     NaN           5.0           0.464117
14   48.55  9.570000      24.209461     2.0          23.0           0.455145
15   46.90  0.000000       0.000000     1.0          31.0           0.465765
16   44.05  5.049999      13.484644     1.0          40.0           0.435553
17   42.70  0.000000       0.000000     2.0           7.0           0.453069
18   40.05  0.000000       0.000000     3.0           8.0           0.429205
19   38.15  0.000000       0.000000     6.0          28.0           0.427313
20   36.00  5.349998      17.219180     5.0         146.0           0.417303
21   33.60  7.040001      26.962854     1.0          33.0           0.399847
22   31.50  0.000000       0.000000    15.0          96.0           0.390051
23   29.25  8.600000      41.346157     2.0          83.0           0.375617
24   26.60  4.840000      21.415930    18.0         236.0           0.350531
25   24.60  5.250000      26.250000     6.0          60.0           0.341437
26   23.00  3.359999      17.573214    15.0         447.0           0.340918
27   22.10  4.400000      24.929176    25.0         175.0           0.355292
28   19.80  2.700001      16.564423    72.0         530.0           0.335608
29   18.75  4.449999      29.966320    27.0         115.0           0.343268
30   17.35  2.349999      17.343168    64.0         390.0           0.341498
31   15.75  4.000000      32.921810    39.0         161.0           0.333930
32   14.50  2.450000      22.171944   344.0        1053.0           0.332709
33   13.25  3.900000      45.882347   113.0          21.0           0.330024
34   11.75  2.350000      26.111115    83.0         514.0           0.320380
35   10.90  1.000000      11.428572    12.0          33.0           0.323646
36    9.50  1.560000      21.399183   131.0         579.0           0.313056
37    8.70  2.100000      35.294125    15.0          12.0           0.314582
38    7.80  1.350000      22.314047    32.0         172.0           0.312293
39    6.95  1.290000      23.888890     6.0          11.0           0.309669
40    6.15  2.120000      48.735630    54.0         594.0           0.306709
41    5.30  2.090000      53.452680     3.0          17.0           0.300666
42    4.80  0.650000      17.105259    46.0         248.0           0.302436
43    3.65  1.190000      46.484380    19.0         257.0           0.297370
44    2.82  0.630000      30.582531    11.0         263.0           0.296028
45    2.25  0.760000      46.913586    18.0         191.0           0.298774
46    1.78  0.310000      25.409830   146.0         658.0           0.301032
47    1.30  0.290000      27.619057   267.0         921.0           0.297737
48    1.13  0.390000      47.560980    19.0         124.0           0.307380
49    0.93  0.070000       9.333332    20.0         112.0           0.312751
50    0.80  0.300000      60.000004     6.0          17.0           0.320563
51    0.75  0.170000      31.481474     5.0         105.0           0.333503
52    0.63  0.140000      29.166672     1.0          36.0           0.338996
53     NaN  0.000000       0.000000     NaN           NaN           0.000000

    inTheMoney contractSize currency
0         True      REGULAR      USD
1         True      REGULAR      USD
2         True      REGULAR      USD
3         True      REGULAR      USD
4         True      REGULAR      USD
5         True      REGULAR      USD
6         True      REGULAR      USD
7         True      REGULAR      USD
8         True      REGULAR      USD
9         True      REGULAR      USD
10        True      REGULAR      USD
11        True      REGULAR      USD
12        True      REGULAR      USD
13        True      REGULAR      USD
14        True      REGULAR      USD
15        True      REGULAR      USD
16        True      REGULAR      USD
17        True      REGULAR      USD
18        True      REGULAR      USD
19        True      REGULAR      USD
20        True      REGULAR      USD
21        True      REGULAR      USD
22        True      REGULAR      USD
23        True      REGULAR      USD
24        True      REGULAR      USD
25        True      REGULAR      USD
26        True      REGULAR      USD
27        True      REGULAR      USD
28        True      REGULAR      USD
29        True      REGULAR      USD
30        True      REGULAR      USD
31        True      REGULAR      USD
32       False      REGULAR      USD
33       False      REGULAR      USD
34       False      REGULAR      USD
35       False      REGULAR      USD
36       False      REGULAR      USD
37       False      REGULAR      USD
38       False      REGULAR      USD
39       False      REGULAR      USD
40       False      REGULAR      USD
41       False      REGULAR      USD
42       False      REGULAR      USD
43       False      REGULAR      USD
44       False      REGULAR      USD
45       False      REGULAR      USD
46       False      REGULAR      USD
47       False      REGULAR      USD
48       False      REGULAR      USD
49       False      REGULAR      USD
50       False      REGULAR      USD
51       False      REGULAR      USD
52       False      REGULAR      USD
53       False      REGULAR      USD  , puts=         contractSymbol       lastTradeDate  strike  lastPrice    bid    ask  \
0   AAPL200724P00180000 2020-06-15 14:17:59   180.0       0.20   0.00   0.18
1   AAPL200724P00190000 2020-06-15 16:28:26   190.0       0.18   0.00   0.22
2   AAPL200724P00195000 2020-06-15 04:13:08   195.0       0.39   0.00   0.24
3   AAPL200724P00200000 2020-06-15 14:51:12   200.0       0.40   0.03   0.27
4   AAPL200724P00205000 2020-06-12 17:35:31   205.0       0.55   0.06   0.31
5   AAPL200724P00210000 2020-06-15 18:07:35   210.0       0.33   0.09   0.34
6   AAPL200724P00215000 2020-06-12 14:35:13   215.0       0.32   0.13   0.36
7   AAPL200724P00220000 2020-06-16 14:19:25   220.0       0.28   0.15   0.43
8   AAPL200724P00225000 2020-06-15 17:48:53   225.0       0.50   0.29   0.42
9   AAPL200724P00230000 2020-06-16 13:41:27   230.0       0.31   0.27   0.48
10  AAPL200724P00235000 2020-06-15 19:02:49   235.0       0.55   0.33   0.54
11  AAPL200724P00240000 2020-06-16 14:45:43   240.0       0.50   0.39   0.66
12  AAPL200724P00245000 2020-06-15 16:19:52   245.0       0.95   0.51   0.60
13  AAPL200724P00250000 2020-06-16 14:21:24   250.0       0.60   0.62   0.71
14  AAPL200724P00255000 2020-06-16 13:34:33   255.0       0.75   0.68   0.77
15  AAPL200724P00260000 2020-06-15 18:50:59   260.0       1.02   0.80   0.87
16  AAPL200724P00265000 2020-06-15 16:46:00   265.0       1.56   0.94   1.04
17  AAPL200724P00270000 2020-06-16 13:54:33   270.0       1.03   1.07   1.16
18  AAPL200724P00275000 2020-06-16 14:28:54   275.0       1.16   1.20   1.26
19  AAPL200724P00280000 2020-06-16 14:24:07   280.0       1.30   1.36   1.45
20  AAPL200724P00285000 2020-06-16 14:40:41   285.0       1.54   1.63   1.71
21  AAPL200724P00290000 2020-06-16 14:53:03   290.0       1.97   1.75   2.19
22  AAPL200724P00295000 2020-06-16 14:38:46   295.0       2.11   2.14   2.24
23  AAPL200724P00300000 2020-06-16 14:42:06   300.0       2.51   2.44   2.55
24  AAPL200724P00302500 2020-06-15 18:08:06   302.5       3.75   2.84   2.95
25  AAPL200724P00305000 2020-06-16 14:18:05   305.0       2.70   2.91   3.05
26  AAPL200724P00307500 2020-06-16 14:47:04   307.5       3.30   3.15   3.30
27  AAPL200724P00310000 2020-06-16 14:53:22   310.0       3.80   3.60   3.75
28  AAPL200724P00312500 2020-06-16 14:23:20   312.5       3.55   3.75   3.90
29  AAPL200724P00315000 2020-06-16 14:37:47   315.0       3.75   4.20   4.35
30  AAPL200724P00317500 2020-06-16 14:02:47   317.5       4.30   4.60   4.75
31  AAPL200724P00320000 2020-06-16 14:41:41   320.0       4.90   4.90   5.10
32  AAPL200724P00322500 2020-06-16 14:44:40   322.5       5.50   5.70   5.90
33  AAPL200724P00325000 2020-06-16 14:25:42   325.0       5.50   6.15   6.35
34  AAPL200724P00327500 2020-06-16 13:52:39   327.5       6.30   6.45   6.65
35  AAPL200724P00330000 2020-06-16 14:53:49   330.0       7.85   7.05   7.25
36  AAPL200724P00332500 2020-06-15 18:40:54   332.5      10.01   7.70   7.90
37  AAPL200724P00335000 2020-06-16 14:42:10   335.0       8.50   8.40   8.60
38  AAPL200724P00337500 2020-06-16 14:38:16   337.5       9.25   9.20   9.45
39  AAPL200724P00340000 2020-06-16 14:47:25   340.0      10.25  10.10  10.30
40  AAPL200724P00342500 2020-06-16 14:55:09   342.5      12.00  10.95  11.15
41  AAPL200724P00345000 2020-06-16 14:38:05   345.0      11.70  11.95  12.15
42  AAPL200724P00347500 2020-06-16 14:34:02   347.5      12.20  12.90  13.15
43  AAPL200724P00350000 2020-06-16 14:52:08   350.0      14.95  14.05  14.25
44  AAPL200724P00352500 2020-06-16 14:48:20   352.5      15.50  15.20  15.45
45  AAPL200724P00355000 2020-06-16 14:37:49   355.0      15.50  15.45  15.60
46  AAPL200724P00357500 2020-06-16 14:34:02   357.5      16.90  17.95  18.20
47  AAPL200724P00360000 2020-06-12 15:22:06   360.0      28.90  20.15  20.35
48  AAPL200724P00365000 2020-06-10 17:44:00   365.0      21.07  22.15  22.75
49  AAPL200724P00370000 2020-06-11 19:36:28   370.0      36.90  25.55  26.00
50  AAPL200724P00385000 2020-06-10 19:09:30   385.0      35.00  36.15  38.75
51  AAPL200724P00390000 2020-06-15 15:23:22   390.0      54.20  40.15  42.90
52  AAPL200724P00395000 2020-06-10 15:30:40   395.0      44.82  45.90  47.75
53  AAPL200724P00400000 2020-06-15 14:23:33   400.0      64.70  50.50  53.95
54  AAPL200724P00405000 2020-06-12 16:34:25   405.0      66.19  55.30  58.65

      change  percentChange  volume  openInterest  impliedVolatility  \
0   0.000000       0.000000    42.0            22           0.775393
1   0.000000       0.000000    10.0            20           0.732425
2   0.000000       0.000000     NaN             1           0.710940
3   0.000000       0.000000    13.0            14           0.700198
4   0.000000       0.000000     NaN             1           0.689456
5   0.000000       0.000000     1.0             3           0.673831
6   0.000000       0.000000     9.0            10           0.656253
7  -0.070000     -19.999998   105.0             8           0.642582
8   0.000000       0.000000     4.0            14           0.632816
9  -0.140000     -31.111107     1.0             7           0.609379
10  0.000000       0.000000    10.0            14           0.594731
11 -0.440000     -46.808510     2.0            17           0.583989
12  0.000000       0.000000   192.0           192           0.561040
13 -0.260000     -30.232557    12.0           217           0.550053
14 -0.430000     -36.440678     5.0            40           0.530034
15  0.000000       0.000000    44.0           198           0.515386
16  0.000000       0.000000   103.0           163           0.503667
17 -1.020000     -49.756100     5.0           198           0.490972
18 -1.360000     -53.968254     8.0           217           0.470464
19 -0.560000     -30.107530     5.0           512           0.455816
20 -0.580000     -27.358488     2.0           249           0.443853
21 -0.430000     -17.916668     1.0           151           0.441534
22 -0.890000     -29.666670     3.0            88           0.412970
23 -0.840000     -25.074625    19.0           384           0.396674
24  0.000000       0.000000     1.0            29           0.398444
25 -2.900000     -51.785717    27.0           104           0.386237
26 -3.000000     -47.619053     6.0            20           0.379645
27 -1.200000     -24.000000    27.0           311           0.379706
28 -1.960000     -35.571693     4.0            73           0.367804
29 -2.230000     -37.290970    31.0           225           0.365607
30 -4.729999     -52.380947     6.0            71           0.360541
31 -2.050000     -29.496399    15.0           230           0.352912
32 -1.900000     -25.675678     1.0            24           0.357428
33 -2.650000     -32.515335    18.0           170           0.350409
34 -5.349999     -45.922745    13.0           134           0.338447
35 -2.300000     -22.660097    59.0           221           0.333503
36  0.000000       0.000000    12.0            42           0.328620
37 -2.700000     -24.107141    11.0           130           0.323676
38 -3.300000     -26.294823     6.0            52           0.320991
39 -3.270001     -24.186394    18.0           242           0.316901
40 -2.750000     -18.644068     3.0           135           0.311347
41 -4.120000     -26.042984     9.0           103           0.307777
42 -4.200000     -25.609755     2.0            54           0.302680
43 -3.070001     -17.036629    32.0           210           0.298255
44  0.550000       3.678931     7.0             1           0.294441
45 -5.420000     -25.908222    11.0            59           0.265602
46 -5.770001     -25.452143     9.0             1           0.289619
47  0.000000       0.000000    18.0            55           0.302436
48  0.000000       0.000000     NaN             1           0.279426
49  0.000000       0.000000     NaN             3           0.268440
50  0.000000       0.000000     NaN             2           0.281990
51  0.000000       0.000000     2.0             2           0.270149
52  0.000000       0.000000     NaN             2           0.284309
53  0.000000       0.000000     1.0             1           0.359992
54  0.000000       0.000000     1.0             1           0.369086

    inTheMoney contractSize currency
0        False      REGULAR      USD
1        False      REGULAR      USD
2        False      REGULAR      USD
3        False      REGULAR      USD
4        False      REGULAR      USD
5        False      REGULAR      USD
6        False      REGULAR      USD
7        False      REGULAR      USD
8        False      REGULAR      USD
9        False      REGULAR      USD
10       False      REGULAR      USD
11       False      REGULAR      USD
12       False      REGULAR      USD
13       False      REGULAR      USD
14       False      REGULAR      USD
15       False      REGULAR      USD
16       False      REGULAR      USD
17       False      REGULAR      USD
18       False      REGULAR      USD
19       False      REGULAR      USD
20       False      REGULAR      USD
21       False      REGULAR      USD
22       False      REGULAR      USD
23       False      REGULAR      USD
24       False      REGULAR      USD
25       False      REGULAR      USD
26       False      REGULAR      USD
27       False      REGULAR      USD
28       False      REGULAR      USD
29       False      REGULAR      USD
30       False      REGULAR      USD
31       False      REGULAR      USD
32       False      REGULAR      USD
33       False      REGULAR      USD
34       False      REGULAR      USD
35       False      REGULAR      USD
36       False      REGULAR      USD
37       False      REGULAR      USD
38       False      REGULAR      USD
39       False      REGULAR      USD
40       False      REGULAR      USD
41       False      REGULAR      USD

In [ ]:
#### OTHER METHODS NOT USED IN ARTICLE ####

In [50]:
# show actions (dividends, splits)
aapl.actions

            Dividends  Stock Splits
Date
1987-05-11    0.00214           0.0
1987-06-16    0.00000           2.0
1987-08-10    0.00214           0.0
1987-11-17    0.00286           0.0
1988-02-12    0.00286           0.0
...               ...           ...
2019-05-10    0.77000           0.0
2019-08-09    0.77000           0.0
2019-11-07    0.77000           0.0
2020-02-07    0.77000           0.0
2020-05-08    0.82000           0.0

[71 rows x 2 columns]

In [52]:
# show splits
aapl.splits

Date
1987-06-16    2.0
2000-06-21    2.0
2005-02-28    2.0
2014-06-09    7.0
Name: Stock Splits, dtype: float64

In [53]:
# show financials BROKEN
aapl.financials

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [54]:
# show quarterly_financials BROKEN
aapl.quarterly_financials

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [55]:
# show major holders 
aapl.major_holders

        0                                      1
0   0.07%        % of Shares Held by All Insider
1  62.12%       % of Shares Held by Institutions
2  62.16%        % of Float Held by Institutions
3    4296  Number of Institutions Holding Shares

In [56]:
# show institutional holders
aapl.institutional_holders

,Holder,Shares,Date Reported,% Out,Value
0,"Vanguard Group, Inc. (The)",336728608,2020-03-30,0.0777,85626717728
1,Blackrock Inc.,274684501,2020-03-30,0.0634,69849521759
2,"Berkshire Hathaway, Inc",245155566,2020-03-30,0.0566,62340608878
3,State Street Corporation,180558954,2020-03-30,0.0417,45914336412
4,"Advisor Group, Inc.",116768396,2020-03-30,0.0269,29693035418
5,"FMR, LLC",93376233,2020-03-30,0.0215,23744642289
6,"Geode Capital Management, LLC",64178586,2020-03-30,0.0148,16319972633
7,Price (T.Rowe) Associates Inc,56203762,2020-03-30,0.0130,14292054638
8,Northern Trust Corporation,53859611,2020-03-30,0.0124,13695960481
9,Norges Bank Investment Management,46856273,2019-12-30,0.0108,13759344566

In [57]:
# show balance sheet BROKEN
aapl.balance_sheet

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [58]:
# BROKEN
aapl.quarterly_balance_sheet

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [59]:
# show cashflow BROKEN
aapl.cashflow

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [60]:
# BROKEN
aapl.quarterly_cashflow

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [61]:
# show earnings BROKEN
aapl.earnings

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [62]:
# BROKEN
aapl.quarterly_earnings

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [63]:
# show sustainability BROKEN
aapl.sustainability

                                     Value
2020-3
palmOil                              False
controversialWeapons                 False
gambling                             False
socialScore                             13
nuclear                              False
furLeather                           False
alcoholic                            False
gmo                                  False
catholic                             False
socialPercentile                         0
peerCount                               57
governanceScore                      10.26
environmentPercentile                    0
animalTesting                        False
tobacco                              False
totalEsg                             23.82
highestControversy                       3
esgPerformance                    AVG_PERF
coal                                 False
pesticides                           False
adult                                False
percentile                           32.44
peerGroup              Technology Hardware
smallArms                            False
environmentScore                      0.55
governancePercentile                     0
militaryContract                     False

In [64]:
# show analysts recommendations
aapl.recommendations

                                  Firm    To Grade From Grade Action
Date
2012-02-09 08:17:00  Canaccord Genuity         Buy              main
2012-03-08 07:33:00     FBN Securities  Outperform              main
2012-03-13 06:08:00          Jefferies         Buy              main
2012-03-14 06:13:00     Morgan Stanley  Overweight              main
2012-03-14 08:21:00  Canaccord Genuity         Buy              main
...                                ...         ...        ...    ...
2020-06-05 12:43:04            Wedbush  Outperform              main
2020-06-10 11:19:05      Deutsche Bank         Buy              main
2020-06-11 11:04:46               HSBC        Hold     Reduce     up
2020-06-11 12:07:07        Wells Fargo  Overweight              main
2020-06-11 12:16:06  B of A Securities         Buy              main

[705 rows x 4 columns]

In [65]:
# show next event (earnings, etc)
aapl.calendar

                                    0                    1
Earnings Date     2020-07-28 00:00:00  2020-08-03 00:00:00
Earnings Average                 1.99                 1.99
Earnings Low                     1.55                 1.55
Earnings High                     2.3                  2.3
Revenue Average           51368400000          51368400000
Revenue Low               42799000000          42799000000
Revenue High              54517500000          54517500000

In [66]:
# show ISIN code - *experimental*
# ISIN = International Securities Identification Number
aapl.isin

'US0378331005'

In [67]:
# show options expirations
aapl.options

('2020-06-19',
 '2020-06-26',
 '2020-07-02',
 '2020-07-10',
 '2020-07-17',
 '2020-07-24',
 '2020-07-31',
 '2020-08-21',
 '2020-09-18',
 '2020-10-16',
 '2020-11-20',
 '2020-12-18',
 '2021-01-15',
 '2021-06-18',
 '2021-09-17',
 '2022-01-21',
 '2022-06-17',
 '2022-09-16')

In [68]:
# get option chain for specific expiration
opt = aapl.option_chain()
opt

Options(calls=         contractSymbol       lastTradeDate  strike  lastPrice     bid  \
0   AAPL200619C00075000 2020-06-15 19:36:28    75.0     266.60  277.60
1   AAPL200619C00080000 2020-06-15 18:00:55    80.0     261.95  272.60
2   AAPL200619C00085000 2020-06-16 13:35:34    85.0     265.35  267.60
3   AAPL200619C00090000 2020-06-04 19:53:39    90.0     231.40  258.65
4   AAPL200619C00095000 2020-05-28 18:32:40    95.0     227.40  255.70
..                  ...                 ...     ...        ...     ...
92  AAPL200619C00460000 2020-06-16 13:30:10   460.0       0.02    0.00
93  AAPL200619C00470000 2020-06-15 19:08:28   470.0       0.01    0.00
94  AAPL200619C00480000 2020-06-15 19:40:30   480.0       0.01    0.00
95  AAPL200619C00490000 2020-06-15 13:58:25   490.0       0.01    0.00
96  AAPL200619C00500000 2020-06-15 19:40:12   500.0       0.01    0.00

       ask    change  percentChange  volume  openInterest  impliedVolatility  \
0   277.90  0.000000       0.000000      25            25           7.574219
1   272.90  0.000000       0.000000      11            62           7.265626
2   267.90  8.399994       3.269116       2            90           6.974611
3   260.45  0.000000       0.000000      45            81           0.000010
4   257.50  0.000000       0.000000      20             2           4.156255
..     ...       ...            ...     ...           ...                ...
92    0.01  0.010000     100.000000       1          1115           0.781252
93    0.01  0.000000       0.000000      73           784           0.843752
94    0.00  0.000000       0.000000    1458          2121           0.500005
95    0.00  0.000000       0.000000     266           690           0.500005
96    0.00  0.000000       0.000000      81          5053           0.500005

    inTheMoney contractSize currency
0         True      REGULAR      USD
1         True      REGULAR      USD
2         True      REGULAR      USD
3         True      REGULAR      USD
4         True      REGULAR      USD
..         ...          ...      ...
92       False      REGULAR      USD
93       False      REGULAR      USD
94       False      REGULAR      USD
95       False      REGULAR      USD
96       False      REGULAR      USD

[97 rows x 14 columns], puts=         contractSymbol       lastTradeDate  strike  lastPrice     bid  \
0   AAPL200619P00075000 2020-06-15 17:54:33    75.0       0.01    0.00
1   AAPL200619P00080000 2020-06-12 17:45:21    80.0       0.01    0.00
2   AAPL200619P00085000 2020-06-08 17:38:58    85.0       0.01    0.00
3   AAPL200619P00090000 2020-06-10 13:44:56    90.0       0.01    0.00
4   AAPL200619P00095000 2020-06-09 22:56:48    95.0       0.01    0.00
..                  ...                 ...     ...        ...     ...
90  AAPL200619P00460000 2020-06-12 17:04:39   460.0     120.60  107.05
91  AAPL200619P00470000 2020-06-12 17:04:38   470.0     130.60  119.90
92  AAPL200619P00480000 2020-06-15 14:27:51   480.0     144.35  129.50
93  AAPL200619P00490000 2020-06-15 18:00:10   490.0     148.65  137.55
94  AAPL200619P00500000 2020-06-16 13:36:31   500.0     149.20  148.60

       ask     change  percentChange  volume  openInterest  impliedVolatility  \
0     0.01   0.000000       0.000000       4          7941           4.250005
1     0.01   0.000000       0.000000       3          2224           4.125005
2     0.01   0.000000       0.000000      19          2554           3.875000
3     0.01   0.000000       0.000000       1          1436           3.750001
4     1.89   0.000000       0.000000       1           665           6.220705
..     ...        ...            ...     ...           ...                ...
90  108.00   0.000000       0.000000       5             4           0.000010
91  121.05   0.000000       0.000000       5             5           1.801515
92  129.85   0.000000       0.000000      10            16           1.717287
93  137.90   0.000000       0.000000       4            24           0.000010
94  148.95 -10.949997      -6.837339       5            17           1.541018

    inTheMoney contractSize currency
0        False      REGULAR      USD
1        False      REGULAR      USD
2        False      REGULAR      USD
3        False      REGULAR      USD
4        False      REGULAR      USD
..         ...          ...      ...
90        True      REGULAR      USD
91        True      REGULAR      USD
92        True      REGULAR      USD
93        True      REGULAR      USD
94        True      REGULAR      USD

[95 rows x 14 columns])